# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testQt.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys, os, random

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_Enigma(QtGui.QWidget):
    def setupUi(self, Enigma):
        Enigma.setObjectName(_fromUtf8("Enigma"))
        Enigma.setWindowModality(QtCore.Qt.WindowModal)
        Enigma.resize(900, 620)
        Enigma.setMinimumSize(QtCore.QSize(900, 620))
        Enigma.setMaximumSize(QtCore.QSize(900, 620))
        font = QtGui.QFont()
        font.setPointSize(10)
        Enigma.setFont(font)
        Enigma.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("enigma.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Enigma.setWindowIcon(icon)
        Enigma.setAutoFillBackground(False)
        Enigma.setWindowFilePath(_fromUtf8(""))
        self.tabWidget = QtGui.QTabWidget(Enigma)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 892, 565))
        self.tabWidget.setMinimumSize(QtCore.QSize(892, 565))
        self.tabWidget.setMaximumSize(QtCore.QSize(892, 565))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_0_encrypt = QtGui.QWidget()
        self.tab_0_encrypt.setObjectName(_fromUtf8("tab_0_encrypt"))
        self.layoutWidget = QtGui.QWidget(self.tab_0_encrypt)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 871, 521))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_input_encrypt = QtGui.QLabel(self.layoutWidget)
        self.label_input_encrypt.setObjectName(_fromUtf8("label_input_encrypt"))
        self.verticalLayout_6.addWidget(self.label_input_encrypt)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.textEdit_input_encrypt = QtGui.QTextEdit(self.layoutWidget)
        self.textEdit_input_encrypt.setObjectName(_fromUtf8("textEdit_input_encrypt"))
        self.verticalLayout_5.addWidget(self.textEdit_input_encrypt)
        self.pushButton_encrypt = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_encrypt.setObjectName(_fromUtf8("pushButton_encrypt"))
        self.verticalLayout_5.addWidget(self.pushButton_encrypt)
        self.textEdit_output_encrypt = QtGui.QTextEdit(self.layoutWidget)
        self.textEdit_output_encrypt.setObjectName(_fromUtf8("textEdit_output_encrypt"))
        self.verticalLayout_5.addWidget(self.textEdit_output_encrypt)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_0_encrypt, _fromUtf8(""))
        self.tab_1_decrypt = QtGui.QWidget()
        self.tab_1_decrypt.setObjectName(_fromUtf8("tab_1_decrypt"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_1_decrypt)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 871, 521))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_7.addWidget(self.label)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.textEdit_input_decrypt = QtGui.QTextEdit(self.layoutWidget1)
        self.textEdit_input_decrypt.setFrameShape(QtGui.QFrame.StyledPanel)
        self.textEdit_input_decrypt.setObjectName(_fromUtf8("textEdit_input_decrypt"))
        self.verticalLayout_4.addWidget(self.textEdit_input_decrypt)
        self.pushButton_decrypt = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_decrypt.setAutoDefault(False)
        self.pushButton_decrypt.setObjectName(_fromUtf8("pushButton_decrypt"))
        self.verticalLayout_4.addWidget(self.pushButton_decrypt)
        self.textEdit_output_decrypt = QtGui.QTextEdit(self.layoutWidget1)
        self.textEdit_output_decrypt.setObjectName(_fromUtf8("textEdit_output_decrypt"))
        self.verticalLayout_4.addWidget(self.textEdit_output_decrypt)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_1_decrypt, _fromUtf8(""))
        self.tab_2_seting = QtGui.QWidget()
        self.tab_2_seting.setObjectName(_fromUtf8("tab_2_seting"))
        self.groupBox = QtGui.QGroupBox(self.tab_2_seting)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 211, 261))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 160, 211, 81))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.spinBox_quantity_symbol = QtGui.QSpinBox(self.layoutWidget2)
        self.spinBox_quantity_symbol.setProperty("value", 0)
        self.spinBox_quantity_symbol.setObjectName(_fromUtf8("spinBox_quantity_symbol"))
        self.horizontalLayout.addWidget(self.spinBox_quantity_symbol)
        self.label_quantity_symbol = QtGui.QLabel(self.layoutWidget2)
        self.label_quantity_symbol.setObjectName(_fromUtf8("label_quantity_symbol"))
        self.horizontalLayout.addWidget(self.label_quantity_symbol)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBox_lang = QtGui.QComboBox(self.layoutWidget2)
        self.comboBox_lang.setObjectName(_fromUtf8("comboBox_lang"))
        self.comboBox_lang.addItem(_fromUtf8(""))
        self.comboBox_lang.addItem(_fromUtf8(""))
        self.comboBox_lang.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_lang)
        self.label_language = QtGui.QLabel(self.layoutWidget2)
        self.label_language.setObjectName(_fromUtf8("label_language"))
        self.horizontalLayout_2.addWidget(self.label_language)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget3 = QtGui.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 201, 61))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_manually = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButton_manually.setChecked(True)
        self.radioButton_manually.setObjectName(_fromUtf8("radioButton_manually"))
        self.verticalLayout_2.addWidget(self.radioButton_manually)
        self.radioButton_auto = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButton_auto.setObjectName(_fromUtf8("radioButton_auto"))
        self.verticalLayout_2.addWidget(self.radioButton_auto)
        self.pushButton_generate = QtGui.QPushButton(self.groupBox)
        self.pushButton_generate.setGeometry(QtCore.QRect(20, 100, 181, 23))
        self.pushButton_generate.setObjectName(_fromUtf8("pushButton_generate"))
        self.pushButton_generate.setDisabled(True)
        self.layoutWidget4 = QtGui.QWidget(self.tab_2_seting)
        self.layoutWidget4.setGeometry(QtCore.QRect(220, 0, 671, 640))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_symbol = QtGui.QGroupBox(self.layoutWidget4)
        self.groupBox_symbol.setMaximumSize(QtCore.QSize(16777215, 190))
        self.groupBox_symbol.setObjectName(_fromUtf8("groupBox_symbol"))
        self.layoutWidget5 = QtGui.QWidget(self.groupBox_symbol)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 21, 641, 144))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_13.setSpacing(2)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_0 = QtGui.QLabel(self.layoutWidget5)
        self.label_0.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_0.setObjectName(_fromUtf8("label_0"))
        self.horizontalLayout_3.addWidget(self.label_0)
        self.lineEdit_0 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_0.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_0.setObjectName(_fromUtf8("lineEdit_0"))
        self.horizontalLayout_3.addWidget(self.lineEdit_0)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_1 = QtGui.QLabel(self.layoutWidget5)
        self.label_1.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.horizontalLayout_4.addWidget(self.label_1)
        self.lineEdit_1 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_1.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_1.setObjectName(_fromUtf8("lineEdit_1"))
        self.horizontalLayout_4.addWidget(self.lineEdit_1)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget5)
        self.label_2.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.layoutWidget5)
        self.label_3.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.layoutWidget5)
        self.label_4.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.layoutWidget5)
        self.label_5.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_8.addWidget(self.lineEdit_5)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(self.layoutWidget5)
        self.label_6.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_9.addWidget(self.lineEdit_6)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_7 = QtGui.QLabel(self.layoutWidget5)
        self.label_7.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_10.addWidget(self.lineEdit_7)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_8 = QtGui.QLabel(self.layoutWidget5)
        self.label_8.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_11.addWidget(self.label_8)
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_11.addWidget(self.lineEdit_8)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_9 = QtGui.QLabel(self.layoutWidget5)
        self.label_9.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_12.addWidget(self.label_9)
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_12.addWidget(self.lineEdit_9)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_24.setSpacing(2)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_10 = QtGui.QLabel(self.layoutWidget5)
        self.label_10.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_14.addWidget(self.label_10)
        self.lineEdit_10 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_14.addWidget(self.lineEdit_10)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_15.setSpacing(2)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_11 = QtGui.QLabel(self.layoutWidget5)
        self.label_11.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_15.addWidget(self.label_11)
        self.lineEdit_11 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout_15.addWidget(self.lineEdit_11)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_16.setSpacing(2)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_12 = QtGui.QLabel(self.layoutWidget5)
        self.label_12.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_16.addWidget(self.label_12)
        self.lineEdit_12 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_16.addWidget(self.lineEdit_12)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_17.setSpacing(2)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_13 = QtGui.QLabel(self.layoutWidget5)
        self.label_13.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_17.addWidget(self.label_13)
        self.lineEdit_13 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.horizontalLayout_17.addWidget(self.lineEdit_13)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_18.setSpacing(2)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_14 = QtGui.QLabel(self.layoutWidget5)
        self.label_14.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_18.addWidget(self.label_14)
        self.lineEdit_14 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.horizontalLayout_18.addWidget(self.lineEdit_14)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_19.setSpacing(2)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_15 = QtGui.QLabel(self.layoutWidget5)
        self.label_15.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_19.addWidget(self.label_15)
        self.lineEdit_15 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_15.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.horizontalLayout_19.addWidget(self.lineEdit_15)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_20.setSpacing(2)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_16 = QtGui.QLabel(self.layoutWidget5)
        self.label_16.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_20.addWidget(self.label_16)
        self.lineEdit_16 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_16.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.horizontalLayout_20.addWidget(self.lineEdit_16)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_21.setSpacing(2)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_17 = QtGui.QLabel(self.layoutWidget5)
        self.label_17.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_21.addWidget(self.label_17)
        self.lineEdit_17 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_17.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.horizontalLayout_21.addWidget(self.lineEdit_17)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_22.setSpacing(2)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_18 = QtGui.QLabel(self.layoutWidget5)
        self.label_18.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_22.addWidget(self.label_18)
        self.lineEdit_18 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_18.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.horizontalLayout_22.addWidget(self.lineEdit_18)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_23.setSpacing(2)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_19 = QtGui.QLabel(self.layoutWidget5)
        self.label_19.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_23.addWidget(self.label_19)
        self.lineEdit_19 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_19.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.horizontalLayout_23.addWidget(self.lineEdit_19)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_23)
        self.verticalLayout_3.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_35.setSpacing(2)
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_25.setSpacing(2)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_20 = QtGui.QLabel(self.layoutWidget5)
        self.label_20.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_25.addWidget(self.label_20)
        self.lineEdit_20 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.horizontalLayout_25.addWidget(self.lineEdit_20)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_26.setSpacing(2)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_21 = QtGui.QLabel(self.layoutWidget5)
        self.label_21.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_26.addWidget(self.label_21)
        self.lineEdit_21 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_21.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.horizontalLayout_26.addWidget(self.lineEdit_21)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_27.setSpacing(2)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_22 = QtGui.QLabel(self.layoutWidget5)
        self.label_22.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_27.addWidget(self.label_22)
        self.lineEdit_22 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.horizontalLayout_27.addWidget(self.lineEdit_22)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_28.setSpacing(2)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_23 = QtGui.QLabel(self.layoutWidget5)
        self.label_23.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_28.addWidget(self.label_23)
        self.lineEdit_23 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_23.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.horizontalLayout_28.addWidget(self.lineEdit_23)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_29.setSpacing(2)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_24 = QtGui.QLabel(self.layoutWidget5)
        self.label_24.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_29.addWidget(self.label_24)
        self.lineEdit_24 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.horizontalLayout_29.addWidget(self.lineEdit_24)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_30.setSpacing(2)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_25 = QtGui.QLabel(self.layoutWidget5)
        self.label_25.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_30.addWidget(self.label_25)
        self.lineEdit_25 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.horizontalLayout_30.addWidget(self.lineEdit_25)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_31.setSpacing(2)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_26 = QtGui.QLabel(self.layoutWidget5)
        self.label_26.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_31.addWidget(self.label_26)
        self.lineEdit_26 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_26.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.horizontalLayout_31.addWidget(self.lineEdit_26)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_32.setSpacing(2)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_27 = QtGui.QLabel(self.layoutWidget5)
        self.label_27.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_32.addWidget(self.label_27)
        self.lineEdit_27 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_27.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.horizontalLayout_32.addWidget(self.lineEdit_27)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_33.setSpacing(2)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_28 = QtGui.QLabel(self.layoutWidget5)
        self.label_28.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_33.addWidget(self.label_28)
        self.lineEdit_28 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_28.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.horizontalLayout_33.addWidget(self.lineEdit_28)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_34.setSpacing(2)
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_29 = QtGui.QLabel(self.layoutWidget5)
        self.label_29.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_34.addWidget(self.label_29)
        self.lineEdit_29 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_29.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.horizontalLayout_34.addWidget(self.lineEdit_29)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_34)
        self.verticalLayout_3.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_36.setSpacing(2)
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_30 = QtGui.QLabel(self.layoutWidget5)
        self.label_30.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_36.addWidget(self.label_30)
        self.lineEdit_30 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_30.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.horizontalLayout_36.addWidget(self.lineEdit_30)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_37.setSpacing(2)
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_31 = QtGui.QLabel(self.layoutWidget5)
        self.label_31.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_37.addWidget(self.label_31)
        self.lineEdit_31 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_31.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.horizontalLayout_37.addWidget(self.lineEdit_31)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_38.setSpacing(2)
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_32 = QtGui.QLabel(self.layoutWidget5)
        self.label_32.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_38.addWidget(self.label_32)
        self.lineEdit_32 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_32.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.horizontalLayout_38.addWidget(self.lineEdit_32)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_38)
        self.verticalLayout_3.addLayout(self.horizontalLayout_39)
        self.verticalLayout_8.addWidget(self.groupBox_symbol)
        self.groupBox_number = QtGui.QGroupBox(self.layoutWidget4)
        self.groupBox_number.setMinimumSize(QtCore.QSize(400, 2))
        self.groupBox_number.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_number.setObjectName(_fromUtf8("groupBox_number"))
        self.layoutWidget6 = QtGui.QWidget(self.groupBox_number)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 20, 641, 41))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_50 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setSpacing(2)
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_num_0 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_0.setObjectName(_fromUtf8("label_num_0"))
        self.horizontalLayout_40.addWidget(self.label_num_0)
        self.lineEdit_num_0 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_0.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_0.setObjectName(_fromUtf8("lineEdit_num_0"))
        self.horizontalLayout_40.addWidget(self.lineEdit_num_0)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setSpacing(2)
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.label_num_1 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_1.setObjectName(_fromUtf8("label_num_1"))
        self.horizontalLayout_41.addWidget(self.label_num_1)
        self.lineEdit_num_1 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_1.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_1.setObjectName(_fromUtf8("lineEdit_num_1"))
        self.horizontalLayout_41.addWidget(self.lineEdit_num_1)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setSpacing(2)
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_num_2 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_2.setObjectName(_fromUtf8("label_num_2"))
        self.horizontalLayout_42.addWidget(self.label_num_2)
        self.lineEdit_num_2 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_2.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_2.setObjectName(_fromUtf8("lineEdit_num_2"))
        self.horizontalLayout_42.addWidget(self.lineEdit_num_2)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setSpacing(2)
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.label_num_3 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_3.setObjectName(_fromUtf8("label_num_3"))
        self.horizontalLayout_43.addWidget(self.label_num_3)
        self.lineEdit_num_3 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_3.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_3.setObjectName(_fromUtf8("lineEdit_num_3"))
        self.horizontalLayout_43.addWidget(self.lineEdit_num_3)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setSpacing(2)
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.label_num_4 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_4.setObjectName(_fromUtf8("label_num_4"))
        self.horizontalLayout_44.addWidget(self.label_num_4)
        self.lineEdit_num_4 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_4.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_4.setObjectName(_fromUtf8("lineEdit_num_4"))
        self.horizontalLayout_44.addWidget(self.lineEdit_num_4)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setSpacing(2)
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.label_num_5 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_5.setObjectName(_fromUtf8("label_num_5"))
        self.horizontalLayout_45.addWidget(self.label_num_5)
        self.lineEdit_num_5 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_5.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_5.setObjectName(_fromUtf8("lineEdit_num_5"))
        self.horizontalLayout_45.addWidget(self.lineEdit_num_5)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setSpacing(2)
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        self.label_num_6 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_6.setObjectName(_fromUtf8("label_num_6"))
        self.horizontalLayout_46.addWidget(self.label_num_6)
        self.lineEdit_num_6 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_6.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_6.setObjectName(_fromUtf8("lineEdit_num_6"))
        self.horizontalLayout_46.addWidget(self.lineEdit_num_6)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setSpacing(2)
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        self.label_num_7 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_7.setObjectName(_fromUtf8("label_num_7"))
        self.horizontalLayout_47.addWidget(self.label_num_7)
        self.lineEdit_num_7 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_7.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_7.setObjectName(_fromUtf8("lineEdit_num_7"))
        self.horizontalLayout_47.addWidget(self.lineEdit_num_7)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtGui.QHBoxLayout()
        self.horizontalLayout_48.setSpacing(2)
        self.horizontalLayout_48.setObjectName(_fromUtf8("horizontalLayout_48"))
        self.label_num_8 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_8.setObjectName(_fromUtf8("label_num_8"))
        self.horizontalLayout_48.addWidget(self.label_num_8)
        self.lineEdit_num_8 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_8.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_8.setObjectName(_fromUtf8("lineEdit_num_8"))
        self.horizontalLayout_48.addWidget(self.lineEdit_num_8)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_49 = QtGui.QHBoxLayout()
        self.horizontalLayout_49.setSpacing(2)
        self.horizontalLayout_49.setObjectName(_fromUtf8("horizontalLayout_49"))
        self.label_num_9 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_9.setObjectName(_fromUtf8("label_num_9"))
        self.horizontalLayout_49.addWidget(self.label_num_9)
        self.lineEdit_num_9 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_9.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_9.setObjectName(_fromUtf8("lineEdit_num_9"))
        self.horizontalLayout_49.addWidget(self.lineEdit_num_9)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_49)
        self.verticalLayout_8.addWidget(self.groupBox_number)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget4)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget7 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 20, 642, 64))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_61 = QtGui.QHBoxLayout()
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.horizontalLayout_51 = QtGui.QHBoxLayout()
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.label_sym_0 = QtGui.QLabel(self.layoutWidget7)
        self.label_sym_0.setObjectName(_fromUtf8("label_sym_0"))
        self.horizontalLayout_51.addWidget(self.label_sym_0)
        self.lineEdit_sym_0 = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_sym_0.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_0.setObjectName(_fromUtf8("lineEdit_sym_0"))
        self.horizontalLayout_51.addWidget(self.lineEdit_sym_0)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_52 = QtGui.QHBoxLayout()
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.label_sym_1 = QtGui.QLabel(self.layoutWidget7)
        self.label_sym_1.setObjectName(_fromUtf8("label_sym_1"))
        self.horizontalLayout_52.addWidget(self.label_sym_1)
        self.lineEdit_sym_1 = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_sym_1.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_1.setObjectName(_fromUtf8("lineEdit_sym_1"))
        self.horizontalLayout_52.addWidget(self.lineEdit_sym_1)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_53 = QtGui.QHBoxLayout()
        self.horizontalLayout_53.setObjectName(_fromUtf8("horizontalLayout_53"))
        self.label_sym_2 = QtGui.QLabel(self.layoutWidget7)
        self.label_sym_2.setObjectName(_fromUtf8("label_sym_2"))
        self.horizontalLayout_53.addWidget(self.label_sym_2)
        self.lineEdit_sym_2 = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_sym_2.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_2.setObjectName(_fromUtf8("lineEdit_sym_2"))
        self.horizontalLayout_53.addWidget(self.lineEdit_sym_2)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_54 = QtGui.QHBoxLayout()
        self.horizontalLayout_54.setObjectName(_fromUtf8("horizontalLayout_54"))
        self.label_sym_3 = QtGui.QLabel(self.layoutWidget7)
        self.label_sym_3.setObjectName(_fromUtf8("label_sym_3"))
        self.horizontalLayout_54.addWidget(self.label_sym_3)
        self.lineEdit_sym_3 = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_sym_3.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_3.setObjectName(_fromUtf8("lineEdit_sym_3"))
        self.horizontalLayout_54.addWidget(self.lineEdit_sym_3)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_55 = QtGui.QHBoxLayout()
        self.horizontalLayout_55.setObjectName(_fromUtf8("horizontalLayout_55"))
        self.label_sym_4 = QtGui.QLabel(self.layoutWidget7)
        self.label_sym_4.setObjectName(_fromUtf8("label_sym_4"))
        self.horizontalLayout_55.addWidget(self.label_sym_4)
        self.lineEdit_sym_4 = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_sym_4.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_4.setObjectName(_fromUtf8("lineEdit_sym_4"))
        self.horizontalLayout_55.addWidget(self.lineEdit_sym_4)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_56 = QtGui.QHBoxLayout()
        self.horizontalLayout_56.setObjectName(_fromUtf8("horizontalLayout_56"))
        self.label_sym_5 = QtGui.QLabel(self.layoutWidget7)
        self.label_sym_5.setObjectName(_fromUtf8("label_sym_5"))
        self.horizontalLayout_56.addWidget(self.label_sym_5)
        self.lineEdit_sym_5 = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_sym_5.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_5.setObjectName(_fromUtf8("lineEdit_sym_5"))
        self.horizontalLayout_56.addWidget(self.lineEdit_sym_5)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_56)
        self.horizontalLayout_57 = QtGui.QHBoxLayout()
        self.horizontalLayout_57.setObjectName(_fromUtf8("horizontalLayout_57"))
        self.label_sym_6 = QtGui.QLabel(self.layoutWidget7)
        self.label_sym_6.setObjectName(_fromUtf8("label_sym_6"))
        self.horizontalLayout_57.addWidget(self.label_sym_6)
        self.lineEdit_sym_6 = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_sym_6.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_6.setObjectName(_fromUtf8("lineEdit_sym_6"))
        self.horizontalLayout_57.addWidget(self.lineEdit_sym_6)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_58 = QtGui.QHBoxLayout()
        self.horizontalLayout_58.setObjectName(_fromUtf8("horizontalLayout_58"))
        self.label_sym_7 = QtGui.QLabel(self.layoutWidget7)
        self.label_sym_7.setObjectName(_fromUtf8("label_sym_7"))
        self.horizontalLayout_58.addWidget(self.label_sym_7)
        self.lineEdit_sym_7 = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_sym_7.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_7.setObjectName(_fromUtf8("lineEdit_sym_7"))
        self.horizontalLayout_58.addWidget(self.lineEdit_sym_7)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_59 = QtGui.QHBoxLayout()
        self.horizontalLayout_59.setObjectName(_fromUtf8("horizontalLayout_59"))
        self.label_sym_8 = QtGui.QLabel(self.layoutWidget7)
        self.label_sym_8.setObjectName(_fromUtf8("label_sym_8"))
        self.horizontalLayout_59.addWidget(self.label_sym_8)
        self.lineEdit_sym_8 = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_sym_8.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_8.setObjectName(_fromUtf8("lineEdit_sym_8"))
        self.horizontalLayout_59.addWidget(self.lineEdit_sym_8)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_60 = QtGui.QHBoxLayout()
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.label_sym_9 = QtGui.QLabel(self.layoutWidget7)
        self.label_sym_9.setObjectName(_fromUtf8("label_sym_9"))
        self.horizontalLayout_60.addWidget(self.label_sym_9)
        self.lineEdit_sym_9 = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_sym_9.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_9.setObjectName(_fromUtf8("lineEdit_sym_9"))
        self.horizontalLayout_60.addWidget(self.lineEdit_sym_9)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_60)
        self.verticalLayout_9.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_64 = QtGui.QHBoxLayout()
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        self.horizontalLayout_62 = QtGui.QHBoxLayout()
        self.horizontalLayout_62.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_62.setSpacing(2)
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.label_sym_10 = QtGui.QLabel(self.layoutWidget7)
        self.label_sym_10.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_sym_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_sym_10.setObjectName(_fromUtf8("label_sym_10"))
        self.horizontalLayout_62.addWidget(self.label_sym_10)
        self.lineEdit_sym_10 = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_sym_10.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_10.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_10.setSizeIncrement(QtCore.QSize(40, 20))
        self.lineEdit_sym_10.setBaseSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_10.setObjectName(_fromUtf8("lineEdit_sym_10"))
        self.horizontalLayout_62.addWidget(self.lineEdit_sym_10)
        self.horizontalLayout_64.addLayout(self.horizontalLayout_62)
        self.horizontalLayout_63 = QtGui.QHBoxLayout()
        self.horizontalLayout_63.setSpacing(2)
        self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        self.label_sym_11 = QtGui.QLabel(self.layoutWidget7)
        self.label_sym_11.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_sym_11.setObjectName(_fromUtf8("label_sym_11"))
        self.horizontalLayout_63.addWidget(self.label_sym_11)
        self.lineEdit_sym_11 = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_sym_11.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_11.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_11.setObjectName(_fromUtf8("lineEdit_sym_11"))
        self.horizontalLayout_63.addWidget(self.lineEdit_sym_11)
        self.horizontalLayout_64.addLayout(self.horizontalLayout_63)
        self.verticalLayout_9.addLayout(self.horizontalLayout_64)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.pushButton_save = QtGui.QPushButton(self.tab_2_seting)
        self.pushButton_save.setGeometry(QtCore.QRect(50, 280, 91, 21))
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.tabWidget.addTab(self.tab_2_seting, _fromUtf8(""))
        self.pushButton_exit = QtGui.QPushButton(Enigma)
        self.pushButton_exit.setGeometry(QtCore.QRect(760, 590, 75, 23))
        self.pushButton_exit.setObjectName(_fromUtf8("pushButton_exit"))

        self.retranslateUi(Enigma)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.radioButton_manually, QtCore.SIGNAL(_fromUtf8("clicked()")), self.manualiti)
        QtCore.QObject.connect(self.radioButton_auto, QtCore.SIGNAL(_fromUtf8("clicked()")), self.auto_gen)
        QtCore.QObject.connect(self.pushButton_generate, QtCore.SIGNAL(_fromUtf8("clicked()")), self.generator)
        QtCore.QObject.connect(self.pushButton_exit, QtCore.SIGNAL(_fromUtf8("clicked()")), Enigma.close)
        QtCore.QObject.connect(self.pushButton_save, QtCore.SIGNAL(_fromUtf8("clicked()")), self.create_file)
        QtCore.QObject.connect(self.spinBox_quantity_symbol, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lokomotiv)
        QtCore.QObject.connect(self.comboBox_lang, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.symbols)
        QtCore.QObject.connect(self.pushButton_encrypt, QtCore.SIGNAL(_fromUtf8("clicked()")), self.encrypt)
        QtCore.QObject.connect(self.pushButton_decrypt, QtCore.SIGNAL(_fromUtf8("clicked()")), self.decrypt)

        QtCore.QMetaObject.connectSlotsByName(Enigma)

    def retranslateUi(self, Enigma):
        Enigma.setWindowTitle(_translate("Enigma", "Enigma", None))
        self.label_input_encrypt.setText(_translate("Enigma", "Введите текст для шифрования:", None))
        self.pushButton_encrypt.setText(_translate("Enigma", "Шивровать", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0_encrypt), _translate("Enigma", "Шифровать", None))
        self.label.setText(_translate("Enigma", "Введите текст для дешифрования:", None))
        self.pushButton_decrypt.setText(_translate("Enigma", "Дешифровать", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1_decrypt), _translate("Enigma", "Дешифровать", None))
        self.groupBox.setTitle(_translate("Enigma", "Настройка заполнения", None))
        self.label_quantity_symbol.setText(_translate("Enigma", "Количество символов", None))
        self.comboBox_lang.setItemText(0, _translate("Enigma", "UA", None))
        self.comboBox_lang.setItemText(1, _translate("Enigma", "EN", None))
        self.comboBox_lang.setItemText(2, _translate("Enigma", "RU", None))
        self.label_language.setText(_translate("Enigma", "Язык", None))
        self.radioButton_manually.setText(_translate("Enigma", "Заполнить вручную", None))
        self.radioButton_auto.setText(_translate("Enigma", "Заполнить автоматически", None))
        self.pushButton_generate.setText(_translate("Enigma", "Генерировать", None))
        self.groupBox_symbol.setTitle(_translate("Enigma", "Буквы", None))
        self.label_0.setText(_translate("Enigma", "А:", None))
        self.label_1.setText(_translate("Enigma", "Б:", None))
        self.label_2.setText(_translate("Enigma", "В:", None))
        self.label_3.setText(_translate("Enigma", "Г:", None))
        self.label_4.setText(_translate("Enigma", "Ґ:", None))
        self.label_5.setText(_translate("Enigma", "Д:", None))
        self.label_6.setText(_translate("Enigma", "Е:", None))
        self.label_7.setText(_translate("Enigma", "Є:", None))
        self.label_8.setText(_translate("Enigma", "Ж:", None))
        self.label_9.setText(_translate("Enigma", "З:", None))
        self.label_10.setText(_translate("Enigma", "И:", None))
        self.label_11.setText(_translate("Enigma", "І:", None))
        self.label_12.setText(_translate("Enigma", "Ї:", None))
        self.label_13.setText(_translate("Enigma", "Й:", None))
        self.label_14.setText(_translate("Enigma", "К:", None))
        self.label_15.setText(_translate("Enigma", "Л:", None))
        self.label_16.setText(_translate("Enigma", "М:", None))
        self.label_17.setText(_translate("Enigma", "Н:", None))
        self.label_18.setText(_translate("Enigma", "О:", None))
        self.label_19.setText(_translate("Enigma", "П:", None))
        self.label_20.setText(_translate("Enigma", "Р:", None))
        self.label_21.setText(_translate("Enigma", "С:", None))
        self.label_22.setText(_translate("Enigma", "Т:", None))
        self.label_23.setText(_translate("Enigma", "У:", None))
        self.label_24.setText(_translate("Enigma", "Ф:", None))
        self.label_25.setText(_translate("Enigma", "Х:", None))
        self.label_26.setText(_translate("Enigma", "Ц:", None))
        self.label_27.setText(_translate("Enigma", "Ч:", None))
        self.label_28.setText(_translate("Enigma", "Ш:", None))
        self.label_29.setText(_translate("Enigma", "Щ:", None))
        self.label_30.setText(_translate("Enigma", "Ь:", None))
        self.label_31.setText(_translate("Enigma", "Ю:", None))
        self.label_32.setText(_translate("Enigma", "Я:", None))
        self.groupBox_number.setTitle(_translate("Enigma", "Цифры", None))
        self.label_num_0.setText(_translate("Enigma", "0:", None))
        self.label_num_1.setText(_translate("Enigma", "1:", None))
        self.label_num_2.setText(_translate("Enigma", "2:", None))
        self.label_num_3.setText(_translate("Enigma", "3:", None))
        self.label_num_4.setText(_translate("Enigma", "4:", None))
        self.label_num_5.setText(_translate("Enigma", "5:", None))
        self.label_num_6.setText(_translate("Enigma", "6:", None))
        self.label_num_7.setText(_translate("Enigma", "7:", None))
        self.label_num_8.setText(_translate("Enigma", "8:", None))
        self.label_num_9.setText(_translate("Enigma", "9:", None))
        self.groupBox_2.setTitle(_translate("Enigma", "Символы", None))
        self.label_sym_0.setText(_translate("Enigma", " :", None))
        self.label_sym_1.setText(_translate("Enigma", "!:", None))
        self.label_sym_2.setText(_translate("Enigma", "?:", None))
        self.label_sym_3.setText(_translate("Enigma", ",:", None))
        self.label_sym_4.setText(_translate("Enigma", ".:", None))
        self.label_sym_5.setText(_translate("Enigma", "::", None))
        self.label_sym_6.setText(_translate("Enigma", ";:", None))
        self.label_sym_7.setText(_translate("Enigma", "(:", None))
        self.label_sym_8.setText(_translate("Enigma", "):", None))
        self.label_sym_9.setText(_translate("Enigma", "@:", None))
        self.label_sym_10.setText(_translate("Enigma", "\':", None))
        self.label_sym_11.setText(_translate("Enigma", "/n:", None))
        self.pushButton_save.setText(_translate("Enigma", "Сохранить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2_seting), _translate("Enigma", "Настройка", None))
        self.pushButton_exit.setText(_translate("Enigma", "Выход", None))


    def __init__(self, parent=None):
        QtGui.QWidget.__init__(self, parent)
        self.setupUi(self)

        self.directory =os.path.dirname('config/')
        self.name_file ='.config'

        self.file = open(self.directory +'/'+ self.name_file)
        self.spp = []

        default_lang = 0
        default_len = 2
        self.default_len = default_len

        self.lokomotiv(default_len)

        self.option = default_lang
        self.symbols(default_lang)
        self.spinBox_quantity_symbol.setProperty('value', default_len)


    '''Quantity symbol'''
    def lokomotiv(self, value):
        value = self.spinBox_quantity_symbol.value()

        self.lineEdit_num_0.setMaxLength(int(value))
        self.lineEdit_num_1.setMaxLength(int(value))
        self.lineEdit_num_2.setMaxLength(int(value))
        self.lineEdit_num_3.setMaxLength(int(value))
        self.lineEdit_num_4.setMaxLength(int(value))
        self.lineEdit_num_5.setMaxLength(int(value))
        self.lineEdit_num_6.setMaxLength(int(value))
        self.lineEdit_num_7.setMaxLength(int(value))
        self.lineEdit_num_8.setMaxLength(int(value))
        self.lineEdit_num_9.setMaxLength(int(value))

        self.lineEdit_0.setMaxLength(int(value))
        self.lineEdit_1.setMaxLength(int(value))
        self.lineEdit_2.setMaxLength(int(value))
        self.lineEdit_3.setMaxLength(int(value))
        self.lineEdit_4.setMaxLength(int(value))
        self.lineEdit_5.setMaxLength(int(value))
        self.lineEdit_6.setMaxLength(int(value))
        self.lineEdit_7.setMaxLength(int(value))
        self.lineEdit_8.setMaxLength(int(value))
        self.lineEdit_9.setMaxLength(int(value))
        self.lineEdit_10.setMaxLength(int(value))
        self.lineEdit_11.setMaxLength(int(value))
        self.lineEdit_12.setMaxLength(int(value))
        self.lineEdit_13.setMaxLength(int(value))
        self.lineEdit_14.setMaxLength(int(value))
        self.lineEdit_15.setMaxLength(int(value))
        self.lineEdit_16.setMaxLength(int(value))
        self.lineEdit_17.setMaxLength(int(value))
        self.lineEdit_18.setMaxLength(int(value))
        self.lineEdit_19.setMaxLength(int(value))
        self.lineEdit_20.setMaxLength(int(value))
        self.lineEdit_21.setMaxLength(int(value))
        self.lineEdit_22.setMaxLength(int(value))
        self.lineEdit_23.setMaxLength(int(value))
        self.lineEdit_24.setMaxLength(int(value))
        self.lineEdit_25.setMaxLength(int(value))
        self.lineEdit_26.setMaxLength(int(value))
        self.lineEdit_27.setMaxLength(int(value))
        self.lineEdit_28.setMaxLength(int(value))
        self.lineEdit_29.setMaxLength(int(value))
        self.lineEdit_30.setMaxLength(int(value))
        self.lineEdit_31.setMaxLength(int(value))
        self.lineEdit_32.setMaxLength(int(value))

        self.lineEdit_sym_0.setMaxLength(int(value))
        self.lineEdit_sym_1.setMaxLength(int(value))
        self.lineEdit_sym_2.setMaxLength(int(value))
        self.lineEdit_sym_3.setMaxLength(int(value))
        self.lineEdit_sym_4.setMaxLength(int(value))
        self.lineEdit_sym_5.setMaxLength(int(value))
        self.lineEdit_sym_6.setMaxLength(int(value))
        self.lineEdit_sym_7.setMaxLength(int(value))
        self.lineEdit_sym_8.setMaxLength(int(value))
        self.lineEdit_sym_9.setMaxLength(int(value))

    '''Create file'''
    def create_file(self):
        self.k = []
        n = [self.lineEdit_num_0.text(),
             self.lineEdit_num_1.text(),
             self.lineEdit_num_2.text(),
             self.lineEdit_num_3.text(),
             self.lineEdit_num_4.text(),
             self.lineEdit_num_5.text(),
             self.lineEdit_num_6.text(),
             self.lineEdit_num_7.text(),
             self.lineEdit_num_8.text(),
             self.lineEdit_num_9.text()]

        b = [self.lineEdit_0.text(),self.lineEdit_1.text(),self.lineEdit_2.text(),self.lineEdit_3.text(),
             self.lineEdit_4.text(),self.lineEdit_5.text(),self.lineEdit_6.text(),self.lineEdit_7.text(),
             self.lineEdit_8.text(),self.lineEdit_9.text(),self.lineEdit_10.text(),self.lineEdit_11.text(),
             self.lineEdit_12.text(),self.lineEdit_13.text(),self.lineEdit_14.text(),self.lineEdit_15.text(),
             self.lineEdit_16.text(),self.lineEdit_17.text(),self.lineEdit_18.text(),self.lineEdit_19.text(),
             self.lineEdit_20.text(),self.lineEdit_21.text(),self.lineEdit_22.text(),self.lineEdit_23.text(),
             self.lineEdit_24.text(),self.lineEdit_25.text(),self.lineEdit_26.text(),self.lineEdit_27.text(),
             self.lineEdit_28.text(),self.lineEdit_29.text(),self.lineEdit_30.text(),self.lineEdit_31.text(),
             self.lineEdit_32.text()]

        s = [self.lineEdit_sym_0.text(),self.lineEdit_sym_1.text(),self.lineEdit_sym_2.text(),self.lineEdit_sym_3.text(),self.lineEdit_sym_4.text(),
             self.lineEdit_sym_5.text(),self.lineEdit_sym_6.text(),self.lineEdit_sym_7.text(),self.lineEdit_sym_8.text(), self.lineEdit_sym_9.text(),
             self.lineEdit_sym_10.text(),self.lineEdit_sym_11.text()]

        for bi in b:
            if not bi:
                pass
            else:
                self.k.append(bi)
        for ni in n:
            if not ni:
                pass
            else:
                self.k.append(ni)
        for si in s:
            if not si:
                pass
            else:
                self.k.append(si)

        self.SaveSetings(self.k)

    def symbols(self, option):
        self.option = self.comboBox_lang.currentIndex()

        if self.option == 0:
            self.name_lan= 'ua'
            self.trol = open(self.directory + '/' + 'ua' + self.name_file)
            for ex in self.trol.readlines():
                self.spp.append(ex)
            self.r = self.spp
            print('UA')
            symbol_ua = ['а', 'б', 'в', 'г', 'ґ', 'д', 'е', 'є', 'ж', 'з', 'и', 'і', 'ї', 'й', 'к', 'л',
                         'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ь', 'ю',
                         'я', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ', '!', '?', ',', '.', ':', ';',
                         '(', ')', '@', "'", '\n']
            self.symbol = symbol_ua
            symbol_gen_ua = ['а', 'б', 'в', 'г', 'ґ', 'д', 'е', 'є', 'ж', 'з', 'и', 'і', 'ї', 'й', 'к', 'л',
                          'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ь', 'ю',
                          'я', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '/', '!', '?', ',', '.', ':', ';',
                          '(', ')', '@', "'", '>']
            self.symbol_gen = symbol_gen_ua
            if len(self.spp) == len(symbol_ua):
                self.output_ua()
            else:
                pass

        elif self.option == 1:
            self.name_lan = 'en'
            self.spp=[]
            self.trol = open(self.directory + '/' + 'en' + self.name_file)
            for ex in self.trol.readlines():
                self.spp.append(ex)
            print('EU')
            print(len(self.spp))

            symbol_en = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
                         'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
                         '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ', '!', '?', ',', '.', ':', ';', '(', ')', '@', "'", "\n"]
            self.symbol= symbol_en
            self.symbol_en = symbol_en

            symbol_gen_en = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
                         'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
                         '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '/', '!', '?', ',', '.', ':', ';', '(', ')', '@', "'", ">"]
            self.symbol_gen = symbol_gen_en
            if len(self.spp) == len(symbol_en):
                self.output_en()

            self.label_26.setText(''),self.label_27.setText('')
            self.label_28.setText(''),self.label_29.setText('')
            self.label_30.setText(''),self.label_31.setText('')

            self.lineEdit_26.setText(''),self.lineEdit_27.setText(''),self.lineEdit_28.setText('')
            self.lineEdit_29.setText(''),self.lineEdit_30.setText(''),self.lineEdit_31.setText(''),self.lineEdit_32.setText('')

            self.label_32.setText(''),self.lineEdit_26.setDisabled(True)
            self.lineEdit_27.setDisabled(True),self.lineEdit_28.setDisabled(True)
            self.lineEdit_29.setDisabled(True),self.lineEdit_30.setDisabled(True)
            self.lineEdit_31.setDisabled(True),self.lineEdit_32.setDisabled(True)

        elif self.option == 2:
            self.name_lan = 'ru'
            self.trol = open(self.directory + '/' + 'ru' + self.name_file)
            for ex in self.trol.readlines():
                self.spp.append(ex)
            print('RU')
            symbol_ru = []
            self.symbol = symbol_ru

    def file_open(self):
        self.drop = []
        self.troling = open(self.directory + '/' + self.name_lan + self.name_file)

        for ex in self.troling.readlines():
            self.drop.append(ex)
        print(self.drop)

    def encrypt(self):
        lst = []
        file = open(self.directory +'/'+self.name_lan+ self.name_file)
        text_encrypt = self.textEdit_input_encrypt.toPlainText()
        if not text_encrypt:
            self.textEdit_input_encrypt.setStyleSheet("color: rgb(255, 0, 255);")
            self.textEdit_input_encrypt.setPlainText('Error: Введите текст!')
        else:
            for line in file.readlines():
                lst.append(line)

        '''Шифрование текста'''
        o_lst = []
        for i in text_encrypt.lower():
            for z in range(0, len(self.symbol)):
                for l in self.symbol[z]:
                    if i == l:
                        o_lst.append(lst[z])
        str_f = ''.join(o_lst).split()
        '''Конец шифрования текста'''

        '''Вывод шифрованого текста'''
        self.textEdit_output_encrypt.setPlainText(''.join(str_f))
        '''Конец вывода шифрованого текста'''

    def decrypt(self):

        self.text_decrypt = self.textEdit_input_decrypt.toPlainText()
        if not self.text_decrypt:
            self.textEdit_input_decrypt.setStyleSheet("color: rgb(255, 0, 255);")
            self.textEdit_input_decrypt.setPlainText('Error: Введите текст!')
        else:
            self.bro = ''.join(self.drop).split()
            t =[]

            for j in [self.text_decrypt.lower()[i:i+self.spinBox_quantity_symbol.value()] for i in range(0, len(self.text_decrypt), self.spinBox_quantity_symbol.value())]:
                for z in range(len(self.symbol)):
                    for l in self.bro[z:z+1]:
                        if j == l:
                            t.append(self.symbol[z])
            self.textEdit_output_decrypt.setPlainText(''.join(t))

    ''' Save settings to file '''
    def SaveSetings(self, k):
        if self.option == 0:
            f = open(self.directory +'/'+ 'ua' + self.name_file, "w")#, encoding="utf-8")
            for z in k:
                f.write(str("%s\n" % z))
            f.close()
        elif self.option == 1:
            f = open(self.directory +'/'+ 'en' + self.name_file, "w")#, encoding="utf-8")
            for z in k:
                f.write(str("%s\n" % z))
            f.close()
        elif self.option == 2:
            f = open(self.directory +'/'+ 'ru' + self.name_file, "w")#, encoding="utf-8")
            for z in k:
                f.write(str("%s\n" % z))
            f.close()
        return self.file_open()



    def manualiti(self):
        self.pushButton_generate.setDisabled(True)
        self.lineEdit_0.setDisabled(False)
        self.lineEdit_1.setDisabled(False)
        self.lineEdit_2.setDisabled(False)
        self.lineEdit_3.setDisabled(False)
        self.lineEdit_4.setDisabled(False)
        self.lineEdit_5.setDisabled(False)
        self.lineEdit_6.setDisabled(False)
        self.lineEdit_7.setDisabled(False)
        self.lineEdit_8.setDisabled(False)
        self.lineEdit_9.setDisabled(False)
        self.lineEdit_10.setDisabled(False)
        self.lineEdit_11.setDisabled(False)
        self.lineEdit_12.setDisabled(False)
        self.lineEdit_13.setDisabled(False)
        self.lineEdit_14.setDisabled(False)
        self.lineEdit_15.setDisabled(False)
        self.lineEdit_16.setDisabled(False)
        self.lineEdit_17.setDisabled(False)
        self.lineEdit_18.setDisabled(False)
        self.lineEdit_19.setDisabled(False)
        self.lineEdit_20.setDisabled(False)
        self.lineEdit_21.setDisabled(False)
        self.lineEdit_22.setDisabled(False)
        self.lineEdit_23.setDisabled(False)
        self.lineEdit_24.setDisabled(False)
        self.lineEdit_25.setDisabled(False)
        self.lineEdit_26.setDisabled(False)
        self.lineEdit_27.setDisabled(False)
        self.lineEdit_28.setDisabled(False)
        self.lineEdit_29.setDisabled(False)
        self.lineEdit_30.setDisabled(False)
        self.lineEdit_31.setDisabled(False)
        self.lineEdit_32.setDisabled(False)

        self.lineEdit_num_0.setDisabled(False)
        self.lineEdit_num_1.setDisabled(False)
        self.lineEdit_num_2.setDisabled(False)
        self.lineEdit_num_3.setDisabled(False)
        self.lineEdit_num_4.setDisabled(False)
        self.lineEdit_num_5.setDisabled(False)
        self.lineEdit_num_6.setDisabled(False)
        self.lineEdit_num_7.setDisabled(False)
        self.lineEdit_num_8.setDisabled(False)
        self.lineEdit_num_9.setDisabled(False)

        self.lineEdit_sym_0.setDisabled(False)
        self.lineEdit_sym_1.setDisabled(False)
        self.lineEdit_sym_2.setDisabled(False)
        self.lineEdit_sym_3.setDisabled(False)
        self.lineEdit_sym_4.setDisabled(False)
        self.lineEdit_sym_5.setDisabled(False)
        self.lineEdit_sym_6.setDisabled(False)
        self.lineEdit_sym_7.setDisabled(False)
        self.lineEdit_sym_8.setDisabled(False)
        self.lineEdit_sym_9.setDisabled(False)
        self.lineEdit_sym_10.setDisabled(False)
        self.lineEdit_sym_11.setDisabled(False)

    def auto_gen(self):
        self.pushButton_generate.setDisabled(False)
        self.lineEdit_0.setDisabled(True)
        self.lineEdit_1.setDisabled(True)
        self.lineEdit_2.setDisabled(True)
        self.lineEdit_3.setDisabled(True)
        self.lineEdit_4.setDisabled(True)
        self.lineEdit_5.setDisabled(True)
        self.lineEdit_6.setDisabled(True)
        self.lineEdit_7.setDisabled(True)
        self.lineEdit_8.setDisabled(True)
        self.lineEdit_9.setDisabled(True)
        self.lineEdit_10.setDisabled(True)
        self.lineEdit_11.setDisabled(True)
        self.lineEdit_12.setDisabled(True)
        self.lineEdit_13.setDisabled(True)
        self.lineEdit_14.setDisabled(True)
        self.lineEdit_15.setDisabled(True)
        self.lineEdit_16.setDisabled(True)
        self.lineEdit_17.setDisabled(True)
        self.lineEdit_18.setDisabled(True)
        self.lineEdit_19.setDisabled(True)
        self.lineEdit_20.setDisabled(True)
        self.lineEdit_21.setDisabled(True)
        self.lineEdit_22.setDisabled(True)
        self.lineEdit_23.setDisabled(True)
        self.lineEdit_24.setDisabled(True)
        self.lineEdit_25.setDisabled(True)
        self.lineEdit_26.setDisabled(True)
        self.lineEdit_27.setDisabled(True)
        self.lineEdit_28.setDisabled(True)
        self.lineEdit_29.setDisabled(True)
        self.lineEdit_30.setDisabled(True)
        self.lineEdit_31.setDisabled(True)
        self.lineEdit_32.setDisabled(True)

        self.lineEdit_num_0.setDisabled(True)
        self.lineEdit_num_1.setDisabled(True)
        self.lineEdit_num_2.setDisabled(True)
        self.lineEdit_num_3.setDisabled(True)
        self.lineEdit_num_4.setDisabled(True)
        self.lineEdit_num_5.setDisabled(True)
        self.lineEdit_num_6.setDisabled(True)
        self.lineEdit_num_7.setDisabled(True)
        self.lineEdit_num_8.setDisabled(True)
        self.lineEdit_num_9.setDisabled(True)

        self.lineEdit_sym_0.setDisabled(True)
        self.lineEdit_sym_1.setDisabled(True)
        self.lineEdit_sym_2.setDisabled(True)
        self.lineEdit_sym_3.setDisabled(True)
        self.lineEdit_sym_4.setDisabled(True)
        self.lineEdit_sym_5.setDisabled(True)
        self.lineEdit_sym_6.setDisabled(True)
        self.lineEdit_sym_7.setDisabled(True)
        self.lineEdit_sym_8.setDisabled(True)
        self.lineEdit_sym_9.setDisabled(True)
        self.lineEdit_sym_10.setDisabled(True)
        self.lineEdit_sym_11.setDisabled(True)

    def generator(self):
        print('Generate')
        t = []
        m = 0
        for i in range(len(self.symbol_gen)):
            t.append(''.join(random.sample(self.symbol_gen, int(self.spinBox_quantity_symbol.value()))))
            #print(t)

            if len(t) == len(list(set(t))):
                m +=1
            else:
                m -=1
        if m == len(self.symbol_gen):
            self.r=list(set(t))
            #print(m, r)
            if self.option == 0:
                self.output_ua()
            elif self.option == 1:
                self.output_en()
            elif self.option == 2:
                self.output_ru()
        else:
            print('return')
            return self.generator()


    def output_ua(self):
        self.label_0.setText((self.symbol[0]+':').upper()),self.label_1.setText((self.symbol[1]+':').upper())
        self.label_2.setText((self.symbol[2]+':').upper()),self.label_3.setText((self.symbol[3]+':').upper())
        self.label_4.setText((self.symbol[4]+':').upper()),self.label_5.setText((self.symbol[5]+':').upper())
        self.label_6.setText((self.symbol[6]+':').upper()),self.label_7.setText((self.symbol[7]+':').upper())
        self.label_8.setText((self.symbol[8]+':').upper()),self.label_9.setText((self.symbol[9]+':').upper())
        self.label_10.setText((self.symbol[10]+':').upper()),self.label_11.setText((self.symbol[11]+':').upper())
        self.label_12.setText((self.symbol[12]+':').upper()),self.label_13.setText((self.symbol[13]+':').upper())
        self.label_14.setText((self.symbol[14]+':').upper()),self.label_15.setText((self.symbol[15]+':').upper())
        self.label_16.setText((self.symbol[16]+':').upper()),self.label_17.setText((self.symbol[17]+':').upper())
        self.label_18.setText((self.symbol[18]+':').upper()),self.label_19.setText((self.symbol[19]+':').upper())
        self.label_20.setText((self.symbol[20]+':').upper()), self.label_21.setText((self.symbol[21]+':').upper())
        self.label_22.setText((self.symbol[22]+':').upper()),self.label_23.setText((self.symbol[23]+':').upper())
        self.label_24.setText((self.symbol[24]+':').upper()),self.label_25.setText((self.symbol[25]+':').upper())
        self.label_26.setText((self.symbol[26]+':').upper()),self.label_27.setText((self.symbol[27]+':').upper())
        self.label_28.setText((self.symbol[28]+':').upper()),self.label_29.setText((self.symbol[29]+':').upper())
        self.label_30.setText((self.symbol[30]+':').upper()),self.label_31.setText((self.symbol[31]+':').upper())
        self.label_32.setText((self.symbol[32]+':').upper())

        self.label_num_0.setText(self.symbol[33]+':')
        self.label_num_1.setText(self.symbol[34]+':'),self.label_num_2.setText(self.symbol[35]+':')
        self.label_num_3.setText(self.symbol[36]+':'),self.label_num_4.setText(self.symbol[37]+':')
        self.label_num_5.setText(self.symbol[38]+':'),self.label_num_6.setText(self.symbol[39]+':')
        self.label_num_7.setText(self.symbol[40]+':'),self.label_num_8.setText(self.symbol[41]+':')
        self.label_num_9.setText(self.symbol[42]+':')

        self.label_sym_0.setText(self.symbol[43]+':')
        self.label_sym_1.setText(self.symbol[44]+':'),self.label_sym_2.setText(self.symbol[45]+':')
        self.label_sym_3.setText(self.symbol[46]+':'),self.label_sym_4.setText(self.symbol[47]+':')
        self.label_sym_5.setText(self.symbol[48]+':'),self.label_sym_6.setText(self.symbol[49]+':')
        self.label_sym_7.setText(self.symbol[50]+':'),self.label_sym_8.setText(self.symbol[51]+':')
        self.label_sym_9.setText(self.symbol[52]+':'),self.label_sym_10.setText(self.symbol[53]+':')
        self.label_sym_11.setText('/n:')

        self.lineEdit_0.setText(self.r[0]),self.lineEdit_1.setText(self.r[1]),self.lineEdit_2.setText(self.r[2])
        self.lineEdit_3.setText(self.r[3]),self.lineEdit_4.setText(self.r[4]),self.lineEdit_5.setText(self.r[5])
        self.lineEdit_6.setText(self.r[6]),self.lineEdit_7.setText(self.r[7]),self.lineEdit_8.setText(self.r[8])
        self.lineEdit_9.setText(self.r[9]),self.lineEdit_10.setText(self.r[10]),self.lineEdit_11.setText(self.r[11])
        self.lineEdit_12.setText(self.r[12]),self.lineEdit_13.setText(self.r[13]),self.lineEdit_14.setText(self.r[14])
        self.lineEdit_15.setText(self.r[15]),self.lineEdit_16.setText(self.r[16]),self.lineEdit_17.setText(self.r[17])
        self.lineEdit_18.setText(self.r[18]),self.lineEdit_19.setText(self.r[19]),self.lineEdit_20.setText(self.r[20])
        self.lineEdit_21.setText(self.r[21]),self.lineEdit_22.setText(self.r[22]),self.lineEdit_23.setText(self.r[23])
        self.lineEdit_24.setText(self.r[24]),self.lineEdit_25.setText(self.r[25]),self.lineEdit_26.setText(self.r[26])
        self.lineEdit_27.setText(self.r[27]),self.lineEdit_28.setText(self.r[28]),self.lineEdit_29.setText(self.r[29])
        self.lineEdit_30.setText(self.r[30]),self.lineEdit_31.setText(self.r[31]),self.lineEdit_32.setText(self.r[32])

        self.lineEdit_num_0.setText(self.r[33]),self.lineEdit_num_1.setText(self.r[34]),self.lineEdit_num_2.setText(self.r[35])
        self.lineEdit_num_3.setText(self.r[36]),self.lineEdit_num_4.setText(self.r[37]),self.lineEdit_num_5.setText(self.r[38])
        self.lineEdit_num_6.setText(self.r[39]),self.lineEdit_num_7.setText(self.r[40]),self.lineEdit_num_8.setText(self.r[41])
        self.lineEdit_num_9.setText(self.r[42])

        self.lineEdit_sym_0.setText(self.r[43]),self.lineEdit_sym_1.setText(self.r[44]),self.lineEdit_sym_2.setText(self.r[45])
        self.lineEdit_sym_3.setText(self.r[46]),self.lineEdit_sym_4.setText(self.r[47]),self.lineEdit_sym_5.setText(self.r[48])
        self.lineEdit_sym_6.setText(self.r[49]),self.lineEdit_sym_7.setText(self.r[50]),self.lineEdit_sym_8.setText(self.r[51])
        self.lineEdit_sym_9.setText(self.r[52]),self.lineEdit_sym_10.setText(self.r[53]),self.lineEdit_sym_11.setText(self.r[54])

    def output_en(self):
        self.label_0.setText((self.symbol_en[0]+':').upper()),self.label_1.setText((self.symbol_en[1]+':').upper())
        self.label_2.setText((self.symbol_en[2]+':').upper()),self.label_3.setText((self.symbol_en[3]+':').upper())
        self.label_4.setText((self.symbol_en[4]+':').upper()),self.label_5.setText((self.symbol_en[5]+':').upper())
        self.label_6.setText((self.symbol_en[6]+':').upper()),self.label_7.setText((self.symbol_en[7]+':').upper())
        self.label_8.setText((self.symbol_en[8]+':').upper()),self.label_9.setText((self.symbol_en[9]+':').upper())
        self.label_10.setText((self.symbol_en[10]+':').upper()),self.label_11.setText((self.symbol_en[11]+':').upper())
        self.label_12.setText((self.symbol_en[12]+':').upper()),self.label_13.setText((self.symbol_en[13]+':').upper())
        self.label_14.setText((self.symbol_en[14]+':').upper()),self.label_15.setText((self.symbol_en[15]+':').upper())
        self.label_16.setText((self.symbol_en[16]+':').upper()),self.label_17.setText((self.symbol_en[17]+':').upper())
        self.label_18.setText((self.symbol_en[18]+':').upper()),self.label_19.setText((self.symbol_en[19]+':').upper())
        self.label_20.setText((self.symbol_en[20]+':').upper()),self.label_21.setText((self.symbol_en[21]+':').upper())
        self.label_22.setText((self.symbol_en[22]+':').upper()),self.label_23.setText((self.symbol_en[23]+':').upper())
        self.label_24.setText((self.symbol_en[24]+':').upper()),self.label_25.setText((self.symbol_en[25]+':').upper())

        self.label_num_0.setText(self.symbol_en[26]+':'),self.label_num_1.setText(self.symbol_en[27]+':')
        self.label_num_2.setText(self.symbol_en[28]+':'),self.label_num_3.setText(self.symbol_en[29]+':')
        self.label_num_4.setText(self.symbol_en[30]+':'),self.label_num_5.setText(self.symbol_en[31]+':')
        self.label_num_6.setText(self.symbol_en[32]+':'),self.label_num_7.setText(self.symbol_en[33]+':')
        self.label_num_8.setText(self.symbol_en[34]+':'),self.label_num_9.setText(self.symbol_en[35]+':')

        self.label_sym_0.setText(self.symbol_en[36]+':'),self.label_sym_1.setText(self.symbol_en[37]+':')
        self.label_sym_2.setText(self.symbol_en[38]+':'),self.label_sym_3.setText(self.symbol_en[39]+':')
        self.label_sym_4.setText(self.symbol_en[40]+':'),self.label_sym_5.setText(self.symbol_en[41]+':')
        self.label_sym_6.setText(self.symbol_en[42]+':'),self.label_sym_7.setText(self.symbol_en[43]+':')
        self.label_sym_8.setText(self.symbol_en[44]+':'),self.label_sym_9.setText(self.symbol_en[45]+':')
        self.label_sym_10.setText(self.symbol_en[46]+':'),self.label_sym_11.setText('/n:')

        self.lineEdit_0.setText(self.r[0]),self.lineEdit_1.setText(self.r[1]),self.lineEdit_2.setText(self.r[2])
        self.lineEdit_3.setText(self.r[3]),self.lineEdit_4.setText(self.r[4]),self.lineEdit_5.setText(self.r[5])
        self.lineEdit_6.setText(self.r[6]),self.lineEdit_7.setText(self.r[7]),self.lineEdit_8.setText(self.r[8])
        self.lineEdit_9.setText(self.r[9]),self.lineEdit_10.setText(self.r[10]),self.lineEdit_11.setText(self.r[11])
        self.lineEdit_12.setText(self.r[12]),self.lineEdit_13.setText(self.r[13]),self.lineEdit_14.setText(self.r[14])
        self.lineEdit_15.setText(self.r[15]),self.lineEdit_16.setText(self.r[16]),self.lineEdit_17.setText(self.r[17])
        self.lineEdit_18.setText(self.r[18]),self.lineEdit_19.setText(self.r[19]),self.lineEdit_20.setText(self.r[20])
        self.lineEdit_21.setText(self.r[21]),self.lineEdit_22.setText(self.r[22]),self.lineEdit_23.setText(self.r[23])
        self.lineEdit_24.setText(self.r[24]),self.lineEdit_25.setText(self.r[25])

        self.lineEdit_num_0.setText(self.r[26]),self.lineEdit_num_1.setText(self.r[27]),self.lineEdit_num_2.setText(self.r[28])
        self.lineEdit_num_3.setText(self.r[29]),self.lineEdit_num_4.setText(self.r[30]),self.lineEdit_num_5.setText(self.r[31])
        self.lineEdit_num_6.setText(self.r[32]),self.lineEdit_num_7.setText(self.r[33]),self.lineEdit_num_8.setText(self.r[34])
        self.lineEdit_num_9.setText(self.r[35])

        self.lineEdit_sym_0.setText(self.r[36]),self.lineEdit_sym_1.setText(self.r[37]),self.lineEdit_sym_2.setText(self.r[38])
        self.lineEdit_sym_3.setText(self.r[39]),self.lineEdit_sym_4.setText(self.r[40]),self.lineEdit_sym_5.setText(self.r[41])
        self.lineEdit_sym_6.setText(self.r[42]),self.lineEdit_sym_7.setText(self.r[43]),self.lineEdit_sym_8.setText(self.r[44])
        self.lineEdit_sym_9.setText(self.r[45]),self.lineEdit_sym_10.setText(self.r[46]),self.lineEdit_sym_11.setText(self.r[47])

    def output_ru(self):
        pass


if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    window = Ui_Enigma()
    window.show()
    sys.exit(app.exec_())
