# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testQt.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Enigma(object):
    def setupUi(self, Enigma):
        Enigma.setObjectName(_fromUtf8("Enigma"))
        Enigma.setWindowModality(QtCore.Qt.WindowModal)
        Enigma.resize(900, 620)
        Enigma.setMinimumSize(QtCore.QSize(900, 620))
        Enigma.setMaximumSize(QtCore.QSize(900, 620))
        font = QtGui.QFont()
        font.setPointSize(10)
        Enigma.setFont(font)
        Enigma.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("enigma.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Enigma.setWindowIcon(icon)
        Enigma.setAutoFillBackground(False)
        Enigma.setWindowFilePath(_fromUtf8(""))
        self.tabWidget = QtGui.QTabWidget(Enigma)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 892, 565))
        self.tabWidget.setMinimumSize(QtCore.QSize(892, 565))
        self.tabWidget.setMaximumSize(QtCore.QSize(892, 565))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_0_encrypt = QtGui.QWidget()
        self.tab_0_encrypt.setObjectName(_fromUtf8("tab_0_encrypt"))
        self.layoutWidget = QtGui.QWidget(self.tab_0_encrypt)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 871, 521))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_input_encrypt = QtGui.QLabel(self.layoutWidget)
        self.label_input_encrypt.setObjectName(_fromUtf8("label_input_encrypt"))
        self.verticalLayout_6.addWidget(self.label_input_encrypt)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.textEdit_input_encrypt = QtGui.QTextEdit(self.layoutWidget)
        self.textEdit_input_encrypt.setObjectName(_fromUtf8("textEdit_input_encrypt"))
        self.verticalLayout_5.addWidget(self.textEdit_input_encrypt)
        self.pushButton_encrypt = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_encrypt.setObjectName(_fromUtf8("pushButton_encrypt"))
        self.verticalLayout_5.addWidget(self.pushButton_encrypt)
        self.textEdit_output_encrypt = QtGui.QTextEdit(self.layoutWidget)
        self.textEdit_output_encrypt.setObjectName(_fromUtf8("textEdit_output_encrypt"))
        self.verticalLayout_5.addWidget(self.textEdit_output_encrypt)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_0_encrypt, _fromUtf8(""))
        self.tab_1_decrypt = QtGui.QWidget()
        self.tab_1_decrypt.setObjectName(_fromUtf8("tab_1_decrypt"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_1_decrypt)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 871, 521))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_7.addWidget(self.label)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.textEdit_input_decrypt = QtGui.QTextEdit(self.layoutWidget1)
        self.textEdit_input_decrypt.setFrameShape(QtGui.QFrame.StyledPanel)
        self.textEdit_input_decrypt.setObjectName(_fromUtf8("textEdit_input_decrypt"))
        self.verticalLayout_4.addWidget(self.textEdit_input_decrypt)
        self.pushButton_decrypt = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_decrypt.setAutoDefault(False)
        self.pushButton_decrypt.setObjectName(_fromUtf8("pushButton_decrypt"))
        self.verticalLayout_4.addWidget(self.pushButton_decrypt)
        self.textEdit_output_decrypt = QtGui.QTextEdit(self.layoutWidget1)
        self.textEdit_output_decrypt.setObjectName(_fromUtf8("textEdit_output_decrypt"))
        self.verticalLayout_4.addWidget(self.textEdit_output_decrypt)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_1_decrypt, _fromUtf8(""))
        self.tab_2_seting = QtGui.QWidget()
        self.tab_2_seting.setObjectName(_fromUtf8("tab_2_seting"))
        self.groupBox = QtGui.QGroupBox(self.tab_2_seting)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 211, 211))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 90, 201, 81))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.spinBox_quantity_symbol = QtGui.QSpinBox(self.layoutWidget2)
        self.spinBox_quantity_symbol.setProperty("value", 0)
        self.spinBox_quantity_symbol.setObjectName(_fromUtf8("spinBox_quantity_symbol"))
        self.horizontalLayout.addWidget(self.spinBox_quantity_symbol)
        self.label_quantity_symbol = QtGui.QLabel(self.layoutWidget2)
        self.label_quantity_symbol.setObjectName(_fromUtf8("label_quantity_symbol"))
        self.horizontalLayout.addWidget(self.label_quantity_symbol)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBox_lang = QtGui.QComboBox(self.layoutWidget2)
        self.comboBox_lang.setObjectName(_fromUtf8("comboBox_lang"))
        self.comboBox_lang.addItem(_fromUtf8(""))
        self.comboBox_lang.addItem(_fromUtf8(""))
        self.comboBox_lang.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_lang)
        self.label_language = QtGui.QLabel(self.layoutWidget2)
        self.label_language.setObjectName(_fromUtf8("label_language"))
        self.horizontalLayout_2.addWidget(self.label_language)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget3 = QtGui.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 201, 61))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_manually = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButton_manually.setObjectName(_fromUtf8("radioButton_manually"))
        self.verticalLayout_2.addWidget(self.radioButton_manually)
        self.radioButton_auto = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButton_auto.setObjectName(_fromUtf8("radioButton_auto"))
        self.verticalLayout_2.addWidget(self.radioButton_auto)
        self.layoutWidget4 = QtGui.QWidget(self.tab_2_seting)
        self.layoutWidget4.setGeometry(QtCore.QRect(220, 0, 671, 640))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_symbol = QtGui.QGroupBox(self.layoutWidget4)
        self.groupBox_symbol.setMaximumSize(QtCore.QSize(16777215, 190))
        self.groupBox_symbol.setObjectName(_fromUtf8("groupBox_symbol"))
        self.layoutWidget5 = QtGui.QWidget(self.groupBox_symbol)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 21, 641, 144))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_13.setSpacing(2)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_0 = QtGui.QLabel(self.layoutWidget5)
        self.label_0.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_0.setObjectName(_fromUtf8("label_0"))
        self.horizontalLayout_3.addWidget(self.label_0)
        self.lineEdit_0 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_0.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_0.setObjectName(_fromUtf8("lineEdit_0"))
        self.horizontalLayout_3.addWidget(self.lineEdit_0)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_1 = QtGui.QLabel(self.layoutWidget5)
        self.label_1.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.horizontalLayout_4.addWidget(self.label_1)
        self.lineEdit_1 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_1.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_1.setObjectName(_fromUtf8("lineEdit_1"))
        self.horizontalLayout_4.addWidget(self.lineEdit_1)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget5)
        self.label_2.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.layoutWidget5)
        self.label_3.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.layoutWidget5)
        self.label_4.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.layoutWidget5)
        self.label_5.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_8.addWidget(self.lineEdit_5)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(self.layoutWidget5)
        self.label_6.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_9.addWidget(self.lineEdit_6)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_7 = QtGui.QLabel(self.layoutWidget5)
        self.label_7.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_10.addWidget(self.lineEdit_7)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_8 = QtGui.QLabel(self.layoutWidget5)
        self.label_8.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_11.addWidget(self.label_8)
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_11.addWidget(self.lineEdit_8)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_9 = QtGui.QLabel(self.layoutWidget5)
        self.label_9.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_12.addWidget(self.label_9)
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_12.addWidget(self.lineEdit_9)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_24.setSpacing(2)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_10 = QtGui.QLabel(self.layoutWidget5)
        self.label_10.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_14.addWidget(self.label_10)
        self.lineEdit_10 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_14.addWidget(self.lineEdit_10)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_15.setSpacing(2)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_11 = QtGui.QLabel(self.layoutWidget5)
        self.label_11.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_15.addWidget(self.label_11)
        self.lineEdit_11 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout_15.addWidget(self.lineEdit_11)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_16.setSpacing(2)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_12 = QtGui.QLabel(self.layoutWidget5)
        self.label_12.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_16.addWidget(self.label_12)
        self.lineEdit_12 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_16.addWidget(self.lineEdit_12)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_17.setSpacing(2)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_13 = QtGui.QLabel(self.layoutWidget5)
        self.label_13.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_17.addWidget(self.label_13)
        self.lineEdit_13 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.horizontalLayout_17.addWidget(self.lineEdit_13)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_18.setSpacing(2)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_14 = QtGui.QLabel(self.layoutWidget5)
        self.label_14.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_18.addWidget(self.label_14)
        self.lineEdit_14 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.horizontalLayout_18.addWidget(self.lineEdit_14)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_19.setSpacing(2)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_15 = QtGui.QLabel(self.layoutWidget5)
        self.label_15.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_19.addWidget(self.label_15)
        self.lineEdit_15 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_15.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.horizontalLayout_19.addWidget(self.lineEdit_15)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_20.setSpacing(2)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_16 = QtGui.QLabel(self.layoutWidget5)
        self.label_16.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_20.addWidget(self.label_16)
        self.lineEdit_16 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_16.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.horizontalLayout_20.addWidget(self.lineEdit_16)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_21.setSpacing(2)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_17 = QtGui.QLabel(self.layoutWidget5)
        self.label_17.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_21.addWidget(self.label_17)
        self.lineEdit_17 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_17.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.horizontalLayout_21.addWidget(self.lineEdit_17)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_22.setSpacing(2)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_18 = QtGui.QLabel(self.layoutWidget5)
        self.label_18.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_22.addWidget(self.label_18)
        self.lineEdit_18 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_18.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.horizontalLayout_22.addWidget(self.lineEdit_18)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_23.setSpacing(2)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_19 = QtGui.QLabel(self.layoutWidget5)
        self.label_19.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_23.addWidget(self.label_19)
        self.lineEdit_19 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_19.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.horizontalLayout_23.addWidget(self.lineEdit_19)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_23)
        self.verticalLayout_3.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_35.setSpacing(2)
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_25.setSpacing(2)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_20 = QtGui.QLabel(self.layoutWidget5)
        self.label_20.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_25.addWidget(self.label_20)
        self.lineEdit_20 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.horizontalLayout_25.addWidget(self.lineEdit_20)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_26.setSpacing(2)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_21 = QtGui.QLabel(self.layoutWidget5)
        self.label_21.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_26.addWidget(self.label_21)
        self.lineEdit_21 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_21.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.horizontalLayout_26.addWidget(self.lineEdit_21)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_27.setSpacing(2)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_22 = QtGui.QLabel(self.layoutWidget5)
        self.label_22.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_27.addWidget(self.label_22)
        self.lineEdit_22 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.horizontalLayout_27.addWidget(self.lineEdit_22)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_28.setSpacing(2)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_23 = QtGui.QLabel(self.layoutWidget5)
        self.label_23.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_28.addWidget(self.label_23)
        self.lineEdit_23 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_23.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.horizontalLayout_28.addWidget(self.lineEdit_23)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_29.setSpacing(2)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_24 = QtGui.QLabel(self.layoutWidget5)
        self.label_24.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_29.addWidget(self.label_24)
        self.lineEdit_24 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.horizontalLayout_29.addWidget(self.lineEdit_24)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_30.setSpacing(2)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_25 = QtGui.QLabel(self.layoutWidget5)
        self.label_25.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_30.addWidget(self.label_25)
        self.lineEdit_25 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.horizontalLayout_30.addWidget(self.lineEdit_25)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_31.setSpacing(2)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_26 = QtGui.QLabel(self.layoutWidget5)
        self.label_26.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_31.addWidget(self.label_26)
        self.lineEdit_26 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_26.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.horizontalLayout_31.addWidget(self.lineEdit_26)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_32.setSpacing(2)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_27 = QtGui.QLabel(self.layoutWidget5)
        self.label_27.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_32.addWidget(self.label_27)
        self.lineEdit_27 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_27.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.horizontalLayout_32.addWidget(self.lineEdit_27)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_33.setSpacing(2)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_28 = QtGui.QLabel(self.layoutWidget5)
        self.label_28.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_33.addWidget(self.label_28)
        self.lineEdit_28 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_28.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.horizontalLayout_33.addWidget(self.lineEdit_28)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_34.setSpacing(2)
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_29 = QtGui.QLabel(self.layoutWidget5)
        self.label_29.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_34.addWidget(self.label_29)
        self.lineEdit_29 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_29.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.horizontalLayout_34.addWidget(self.lineEdit_29)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_34)
        self.verticalLayout_3.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_36.setSpacing(2)
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_30 = QtGui.QLabel(self.layoutWidget5)
        self.label_30.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_36.addWidget(self.label_30)
        self.lineEdit_30 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_30.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.horizontalLayout_36.addWidget(self.lineEdit_30)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_37.setSpacing(2)
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_31 = QtGui.QLabel(self.layoutWidget5)
        self.label_31.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_37.addWidget(self.label_31)
        self.lineEdit_31 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_31.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.horizontalLayout_37.addWidget(self.lineEdit_31)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_38.setSpacing(2)
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_32 = QtGui.QLabel(self.layoutWidget5)
        self.label_32.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_38.addWidget(self.label_32)
        self.lineEdit_32 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_32.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.horizontalLayout_38.addWidget(self.lineEdit_32)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_38)
        self.verticalLayout_3.addLayout(self.horizontalLayout_39)
        self.verticalLayout_8.addWidget(self.groupBox_symbol)
        self.groupBox_number = QtGui.QGroupBox(self.layoutWidget4)
        self.groupBox_number.setMinimumSize(QtCore.QSize(400, 2))
        self.groupBox_number.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_number.setObjectName(_fromUtf8("groupBox_number"))
        self.layoutWidget6 = QtGui.QWidget(self.groupBox_number)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 20, 641, 41))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_50 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setSpacing(2)
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_num_0 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_0.setObjectName(_fromUtf8("label_num_0"))
        self.horizontalLayout_40.addWidget(self.label_num_0)
        self.lineEdit_num_0 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_0.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_0.setObjectName(_fromUtf8("lineEdit_num_0"))
        self.horizontalLayout_40.addWidget(self.lineEdit_num_0)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setSpacing(2)
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.label_num_1 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_1.setObjectName(_fromUtf8("label_num_1"))
        self.horizontalLayout_41.addWidget(self.label_num_1)
        self.lineEdit_num_1 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_1.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_1.setObjectName(_fromUtf8("lineEdit_num_1"))
        self.horizontalLayout_41.addWidget(self.lineEdit_num_1)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setSpacing(2)
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_num_2 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_2.setObjectName(_fromUtf8("label_num_2"))
        self.horizontalLayout_42.addWidget(self.label_num_2)
        self.lineEdit_num_2 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_2.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_2.setObjectName(_fromUtf8("lineEdit_num_2"))
        self.horizontalLayout_42.addWidget(self.lineEdit_num_2)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setSpacing(2)
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.label_num_3 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_3.setObjectName(_fromUtf8("label_num_3"))
        self.horizontalLayout_43.addWidget(self.label_num_3)
        self.lineEdit_num_3 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_3.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_3.setObjectName(_fromUtf8("lineEdit_num_3"))
        self.horizontalLayout_43.addWidget(self.lineEdit_num_3)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setSpacing(2)
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.label_num_4 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_4.setObjectName(_fromUtf8("label_num_4"))
        self.horizontalLayout_44.addWidget(self.label_num_4)
        self.lineEdit_num_4 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_4.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_4.setObjectName(_fromUtf8("lineEdit_num_4"))
        self.horizontalLayout_44.addWidget(self.lineEdit_num_4)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setSpacing(2)
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.label_num_5 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_5.setObjectName(_fromUtf8("label_num_5"))
        self.horizontalLayout_45.addWidget(self.label_num_5)
        self.lineEdit_num_5 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_5.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_5.setObjectName(_fromUtf8("lineEdit_num_5"))
        self.horizontalLayout_45.addWidget(self.lineEdit_num_5)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setSpacing(2)
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        self.label_num_6 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_6.setObjectName(_fromUtf8("label_num_6"))
        self.horizontalLayout_46.addWidget(self.label_num_6)
        self.lineEdit_num_6 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_6.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_6.setObjectName(_fromUtf8("lineEdit_num_6"))
        self.horizontalLayout_46.addWidget(self.lineEdit_num_6)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setSpacing(2)
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        self.label_num_7 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_7.setObjectName(_fromUtf8("label_num_7"))
        self.horizontalLayout_47.addWidget(self.label_num_7)
        self.lineEdit_num_7 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_7.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_7.setObjectName(_fromUtf8("lineEdit_num_7"))
        self.horizontalLayout_47.addWidget(self.lineEdit_num_7)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtGui.QHBoxLayout()
        self.horizontalLayout_48.setSpacing(2)
        self.horizontalLayout_48.setObjectName(_fromUtf8("horizontalLayout_48"))
        self.label_num_8 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_8.setObjectName(_fromUtf8("label_num_8"))
        self.horizontalLayout_48.addWidget(self.label_num_8)
        self.lineEdit_num_8 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_8.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_8.setObjectName(_fromUtf8("lineEdit_num_8"))
        self.horizontalLayout_48.addWidget(self.lineEdit_num_8)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_49 = QtGui.QHBoxLayout()
        self.horizontalLayout_49.setSpacing(2)
        self.horizontalLayout_49.setObjectName(_fromUtf8("horizontalLayout_49"))
        self.label_num_9 = QtGui.QLabel(self.layoutWidget6)
        self.label_num_9.setObjectName(_fromUtf8("label_num_9"))
        self.horizontalLayout_49.addWidget(self.label_num_9)
        self.lineEdit_num_9 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_num_9.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_num_9.setObjectName(_fromUtf8("lineEdit_num_9"))
        self.horizontalLayout_49.addWidget(self.lineEdit_num_9)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_49)
        self.verticalLayout_8.addWidget(self.groupBox_number)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget4)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.widget = QtGui.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 20, 642, 64))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_61 = QtGui.QHBoxLayout()
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.horizontalLayout_51 = QtGui.QHBoxLayout()
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.label_sym_0 = QtGui.QLabel(self.widget)
        self.label_sym_0.setObjectName(_fromUtf8("label_sym_0"))
        self.horizontalLayout_51.addWidget(self.label_sym_0)
        self.lineEdit_sym_0 = QtGui.QLineEdit(self.widget)
        self.lineEdit_sym_0.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_0.setObjectName(_fromUtf8("lineEdit_sym_0"))
        self.horizontalLayout_51.addWidget(self.lineEdit_sym_0)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_52 = QtGui.QHBoxLayout()
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.label_sym_1 = QtGui.QLabel(self.widget)
        self.label_sym_1.setObjectName(_fromUtf8("label_sym_1"))
        self.horizontalLayout_52.addWidget(self.label_sym_1)
        self.lineEdit_sym_1 = QtGui.QLineEdit(self.widget)
        self.lineEdit_sym_1.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_1.setObjectName(_fromUtf8("lineEdit_sym_1"))
        self.horizontalLayout_52.addWidget(self.lineEdit_sym_1)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_53 = QtGui.QHBoxLayout()
        self.horizontalLayout_53.setObjectName(_fromUtf8("horizontalLayout_53"))
        self.label_sym_2 = QtGui.QLabel(self.widget)
        self.label_sym_2.setObjectName(_fromUtf8("label_sym_2"))
        self.horizontalLayout_53.addWidget(self.label_sym_2)
        self.lineEdit_sym_2 = QtGui.QLineEdit(self.widget)
        self.lineEdit_sym_2.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_2.setObjectName(_fromUtf8("lineEdit_sym_2"))
        self.horizontalLayout_53.addWidget(self.lineEdit_sym_2)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_54 = QtGui.QHBoxLayout()
        self.horizontalLayout_54.setObjectName(_fromUtf8("horizontalLayout_54"))
        self.label_sym_3 = QtGui.QLabel(self.widget)
        self.label_sym_3.setObjectName(_fromUtf8("label_sym_3"))
        self.horizontalLayout_54.addWidget(self.label_sym_3)
        self.lineEdit_sym_3 = QtGui.QLineEdit(self.widget)
        self.lineEdit_sym_3.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_3.setObjectName(_fromUtf8("lineEdit_sym_3"))
        self.horizontalLayout_54.addWidget(self.lineEdit_sym_3)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_55 = QtGui.QHBoxLayout()
        self.horizontalLayout_55.setObjectName(_fromUtf8("horizontalLayout_55"))
        self.label_sym_4 = QtGui.QLabel(self.widget)
        self.label_sym_4.setObjectName(_fromUtf8("label_sym_4"))
        self.horizontalLayout_55.addWidget(self.label_sym_4)
        self.lineEdit_sym_4 = QtGui.QLineEdit(self.widget)
        self.lineEdit_sym_4.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_4.setObjectName(_fromUtf8("lineEdit_sym_4"))
        self.horizontalLayout_55.addWidget(self.lineEdit_sym_4)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_56 = QtGui.QHBoxLayout()
        self.horizontalLayout_56.setObjectName(_fromUtf8("horizontalLayout_56"))
        self.label_sym_5 = QtGui.QLabel(self.widget)
        self.label_sym_5.setObjectName(_fromUtf8("label_sym_5"))
        self.horizontalLayout_56.addWidget(self.label_sym_5)
        self.lineEdit_sym_5 = QtGui.QLineEdit(self.widget)
        self.lineEdit_sym_5.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_5.setObjectName(_fromUtf8("lineEdit_sym_5"))
        self.horizontalLayout_56.addWidget(self.lineEdit_sym_5)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_56)
        self.horizontalLayout_57 = QtGui.QHBoxLayout()
        self.horizontalLayout_57.setObjectName(_fromUtf8("horizontalLayout_57"))
        self.label_sym_6 = QtGui.QLabel(self.widget)
        self.label_sym_6.setObjectName(_fromUtf8("label_sym_6"))
        self.horizontalLayout_57.addWidget(self.label_sym_6)
        self.lineEdit_sym_6 = QtGui.QLineEdit(self.widget)
        self.lineEdit_sym_6.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_6.setObjectName(_fromUtf8("lineEdit_sym_6"))
        self.horizontalLayout_57.addWidget(self.lineEdit_sym_6)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_58 = QtGui.QHBoxLayout()
        self.horizontalLayout_58.setObjectName(_fromUtf8("horizontalLayout_58"))
        self.label_sym_7 = QtGui.QLabel(self.widget)
        self.label_sym_7.setObjectName(_fromUtf8("label_sym_7"))
        self.horizontalLayout_58.addWidget(self.label_sym_7)
        self.lineEdit_sym_7 = QtGui.QLineEdit(self.widget)
        self.lineEdit_sym_7.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_7.setObjectName(_fromUtf8("lineEdit_sym_7"))
        self.horizontalLayout_58.addWidget(self.lineEdit_sym_7)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_59 = QtGui.QHBoxLayout()
        self.horizontalLayout_59.setObjectName(_fromUtf8("horizontalLayout_59"))
        self.label_sym_8 = QtGui.QLabel(self.widget)
        self.label_sym_8.setObjectName(_fromUtf8("label_sym_8"))
        self.horizontalLayout_59.addWidget(self.label_sym_8)
        self.lineEdit_sym_8 = QtGui.QLineEdit(self.widget)
        self.lineEdit_sym_8.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_8.setObjectName(_fromUtf8("lineEdit_sym_8"))
        self.horizontalLayout_59.addWidget(self.lineEdit_sym_8)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_60 = QtGui.QHBoxLayout()
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.label_sym_9 = QtGui.QLabel(self.widget)
        self.label_sym_9.setObjectName(_fromUtf8("label_sym_9"))
        self.horizontalLayout_60.addWidget(self.label_sym_9)
        self.lineEdit_sym_9 = QtGui.QLineEdit(self.widget)
        self.lineEdit_sym_9.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_9.setObjectName(_fromUtf8("lineEdit_sym_9"))
        self.horizontalLayout_60.addWidget(self.lineEdit_sym_9)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_60)
        self.verticalLayout_9.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_64 = QtGui.QHBoxLayout()
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        self.horizontalLayout_62 = QtGui.QHBoxLayout()
        self.horizontalLayout_62.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_62.setSpacing(2)
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.label_sym_10 = QtGui.QLabel(self.widget)
        self.label_sym_10.setMaximumSize(QtCore.QSize(12, 16777215))
        self.label_sym_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_sym_10.setObjectName(_fromUtf8("label_sym_10"))
        self.horizontalLayout_62.addWidget(self.label_sym_10)
        self.lineEdit_sym_10 = QtGui.QLineEdit(self.widget)
        self.lineEdit_sym_10.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_10.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_10.setSizeIncrement(QtCore.QSize(40, 20))
        self.lineEdit_sym_10.setBaseSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_10.setObjectName(_fromUtf8("lineEdit_sym_10"))
        self.horizontalLayout_62.addWidget(self.lineEdit_sym_10)
        self.horizontalLayout_64.addLayout(self.horizontalLayout_62)
        self.horizontalLayout_63 = QtGui.QHBoxLayout()
        self.horizontalLayout_63.setSpacing(2)
        self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        self.label_sym_11 = QtGui.QLabel(self.widget)
        self.label_sym_11.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_sym_11.setObjectName(_fromUtf8("label_sym_11"))
        self.horizontalLayout_63.addWidget(self.label_sym_11)
        self.lineEdit_sym_11 = QtGui.QLineEdit(self.widget)
        self.lineEdit_sym_11.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_11.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_sym_11.setObjectName(_fromUtf8("lineEdit_sym_11"))
        self.horizontalLayout_63.addWidget(self.lineEdit_sym_11)
        self.horizontalLayout_64.addLayout(self.horizontalLayout_63)
        self.verticalLayout_9.addLayout(self.horizontalLayout_64)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.pushButton_save = QtGui.QPushButton(self.tab_2_seting)
        self.pushButton_save.setGeometry(QtCore.QRect(40, 220, 91, 21))
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.tabWidget.addTab(self.tab_2_seting, _fromUtf8(""))
        self.pushButton_exit = QtGui.QPushButton(Enigma)
        self.pushButton_exit.setGeometry(QtCore.QRect(760, 590, 75, 23))
        self.pushButton_exit.setObjectName(_fromUtf8("pushButton_exit"))

        self.retranslateUi(Enigma)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.pushButton_exit, QtCore.SIGNAL(_fromUtf8("clicked()")), Enigma.close)
        QtCore.QMetaObject.connectSlotsByName(Enigma)

    def retranslateUi(self, Enigma):
        Enigma.setWindowTitle(_translate("Enigma", "Enigma", None))
        self.label_input_encrypt.setText(_translate("Enigma", "Введите текст для шифрования:", None))
        self.pushButton_encrypt.setText(_translate("Enigma", "Шивровать", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0_encrypt), _translate("Enigma", "Шифровать", None))
        self.label.setText(_translate("Enigma", "Введите текст для дешифрования:", None))
        self.pushButton_decrypt.setText(_translate("Enigma", "Дешифровать", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1_decrypt), _translate("Enigma", "Дешифровать", None))
        self.groupBox.setTitle(_translate("Enigma", "Настройка заполнения", None))
        self.label_quantity_symbol.setText(_translate("Enigma", "Количество символов", None))
        self.comboBox_lang.setItemText(0, _translate("Enigma", "UA", None))
        self.comboBox_lang.setItemText(1, _translate("Enigma", "EN", None))
        self.comboBox_lang.setItemText(2, _translate("Enigma", "RU", None))
        self.label_language.setText(_translate("Enigma", "Язык", None))
        self.radioButton_manually.setText(_translate("Enigma", "Заполнить вручную", None))
        self.radioButton_auto.setText(_translate("Enigma", "Заполнить автоматически", None))
        self.groupBox_symbol.setTitle(_translate("Enigma", "Буквы", None))
        self.label_0.setText(_translate("Enigma", "А:", None))
        self.label_1.setText(_translate("Enigma", "Б:", None))
        self.label_2.setText(_translate("Enigma", "В:", None))
        self.label_3.setText(_translate("Enigma", "Г:", None))
        self.label_4.setText(_translate("Enigma", "Ґ:", None))
        self.label_5.setText(_translate("Enigma", "Д:", None))
        self.label_6.setText(_translate("Enigma", "Е:", None))
        self.label_7.setText(_translate("Enigma", "Є:", None))
        self.label_8.setText(_translate("Enigma", "Ж:", None))
        self.label_9.setText(_translate("Enigma", "З:", None))
        self.label_10.setText(_translate("Enigma", "И:", None))
        self.label_11.setText(_translate("Enigma", "І:", None))
        self.label_12.setText(_translate("Enigma", "Ї:", None))
        self.label_13.setText(_translate("Enigma", "Й:", None))
        self.label_14.setText(_translate("Enigma", "К:", None))
        self.label_15.setText(_translate("Enigma", "Л:", None))
        self.label_16.setText(_translate("Enigma", "М:", None))
        self.label_17.setText(_translate("Enigma", "Н:", None))
        self.label_18.setText(_translate("Enigma", "О:", None))
        self.label_19.setText(_translate("Enigma", "П:", None))
        self.label_20.setText(_translate("Enigma", "Р:", None))
        self.label_21.setText(_translate("Enigma", "С:", None))
        self.label_22.setText(_translate("Enigma", "Т:", None))
        self.label_23.setText(_translate("Enigma", "У:", None))
        self.label_24.setText(_translate("Enigma", "Ф:", None))
        self.label_25.setText(_translate("Enigma", "Х:", None))
        self.label_26.setText(_translate("Enigma", "Ц:", None))
        self.label_27.setText(_translate("Enigma", "Ч:", None))
        self.label_28.setText(_translate("Enigma", "Ш:", None))
        self.label_29.setText(_translate("Enigma", "Щ:", None))
        self.label_30.setText(_translate("Enigma", "Ь:", None))
        self.label_31.setText(_translate("Enigma", "Ю:", None))
        self.label_32.setText(_translate("Enigma", "Я:", None))
        self.groupBox_number.setTitle(_translate("Enigma", "Цифры", None))
        self.label_num_0.setText(_translate("Enigma", "0:", None))
        self.label_num_1.setText(_translate("Enigma", "1:", None))
        self.label_num_2.setText(_translate("Enigma", "2:", None))
        self.label_num_3.setText(_translate("Enigma", "3:", None))
        self.label_num_4.setText(_translate("Enigma", "4:", None))
        self.label_num_5.setText(_translate("Enigma", "5:", None))
        self.label_num_6.setText(_translate("Enigma", "6:", None))
        self.label_num_7.setText(_translate("Enigma", "7:", None))
        self.label_num_8.setText(_translate("Enigma", "8:", None))
        self.label_num_9.setText(_translate("Enigma", "9:", None))
        self.groupBox_2.setTitle(_translate("Enigma", "Символы", None))
        self.label_sym_0.setText(_translate("Enigma", " :", None))
        self.label_sym_1.setText(_translate("Enigma", "!:", None))
        self.label_sym_2.setText(_translate("Enigma", "?:", None))
        self.label_sym_3.setText(_translate("Enigma", ",:", None))
        self.label_sym_4.setText(_translate("Enigma", ".:", None))
        self.label_sym_5.setText(_translate("Enigma", "::", None))
        self.label_sym_6.setText(_translate("Enigma", ";:", None))
        self.label_sym_7.setText(_translate("Enigma", "(:", None))
        self.label_sym_8.setText(_translate("Enigma", "):", None))
        self.label_sym_9.setText(_translate("Enigma", "@:", None))
        self.label_sym_10.setText(_translate("Enigma", "\':", None))
        self.label_sym_11.setText(_translate("Enigma", "/n:", None))
        self.pushButton_save.setText(_translate("Enigma", "Сохранить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2_seting), _translate("Enigma", "Настройка", None))
        self.pushButton_exit.setText(_translate("Enigma", "Выход", None))

